-- First, make sure you have at least one user
-- Register via: http://localhost:4200/register
-- Then run this script to add sample projects
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "monthlyVisitors",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'متجر ملابس نسائية',
    'متجر متكامل على Shopify مع 150+ منتج ونظام شحن آلي',
    'متجر إلكتروني متكامل متخصص في الملابس النسائية مع قاعدة عملاء مخلصة. يشمل المتجر أكثر من 150 منتج مع نظام شحن آلي ومتكامل مع عدة موردين. المتجر يعمل منذ 3 سنوات ويحقق إيرادات ثابتة شهرياً.',
    'ecommerce',
    'active',
    85000,
    true,
    8500,
    3200,
    45000,
    36,
    'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400',
    ARRAY ['Shopify', 'React', 'Node.js'],
    true,
    156,
    3,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "monthlyVisitors",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'نظام إدارة مطاعم',
    'منصة SaaS لإدارة المطاعم مع 45 عميل نشط',
    'منصة SaaS متكاملة لإدارة المطاعم تشمل نظام طلبات، إدارة المخزون، التقارير، ونقاط البيع. حالياً لديها 45 عميل نشط يدفعون اشتراك شهري. المنصة تعمل منذ عامين وتحقق نمو ثابت.',
    'saas',
    'active',
    120000,
    false,
    4500,
    3200,
    12000,
    24,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    ARRAY ['Laravel', 'Vue.js', 'MySQL'],
    false,
    89,
    2,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'تطبيق توصيل طعام',
    'تطبيق iOS و Android مع 5,000+ مستخدم نشط',
    'تطبيق توصيل طعام كامل مع لوحة تحكم للمطاعم والسائقين. التطبيق متاح على iOS و Android مع قاعدة مستخدمين نشطة تزيد عن 5000 مستخدم. يحقق إيرادات من عمولة الطلبات.',
    'mobile_app',
    'active',
    95000,
    true,
    6800,
    2400,
    18,
    'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400',
    ARRAY ['React Native', 'Firebase', 'Node.js'],
    false,
    67,
    0,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "monthlyVisitors",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'مدونة تقنية',
    'موقع محتوى تقني مع 100,000 زائر شهرياً',
    'مدونة تقنية متخصصة في أخبار البرمجة والتطوير مع زوار شهريين يتجاوزون 100,000. تحقق إيرادات من Google AdSense والمحتوى المدعوم. تحتوي على أكثر من 500 مقال عالي الجودة.',
    'content_site',
    'active',
    45000,
    false,
    2100,
    1800,
    100000,
    48,
    'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=400',
    ARRAY ['WordPress', 'PHP', 'MySQL'],
    false,
    234,
    1,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "monthlyVisitors",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'منصة كورسات أونلاين',
    'موقع تعليمي مع 30 كورس و 2,000 طالب',
    'منصة تعليمية إلكترونية تقدم كورسات في البرمجة والتصميم. تحتوي على 30 كورس مسجل و 2,000 طالب مسجل مع نظام اشتراكات شهري. المنصة تحقق نمو 15% شهرياً.',
    'education',
    'active',
    78000,
    true,
    5200,
    3800,
    28000,
    20,
    'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400',
    ARRAY ['Next.js', 'Stripe', 'PostgreSQL'],
    true,
    145,
    0,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "monthlyVisitors",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'متجر مستحضرات تجميل',
    'متجر دروبشيبينغ مع 500+ منتج',
    'متجر دروبشيبينغ متخصص في مستحضرات التجميل والعناية بالبشرة. متصل مع موردين موثوقين ويحقق مبيعات ثابتة شهرياً. المتجر يعمل بشكل شبه آلي.',
    'ecommerce',
    'active',
    52000,
    true,
    4200,
    2100,
    32000,
    15,
    'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    ARRAY ['WooCommerce', 'WordPress', 'PHP'],
    false,
    98,
    0,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'تطبيق لياقة بدنية',
    'تطبيق تمارين رياضية مع 8,000 مستخدم',
    'تطبيق لياقة بدنية يقدم برامج تمارين مخصصة وخطط تغذية. لديه قاعدة مستخدمين مخلصة تدفع اشتراك شهري. التطبيق يتضمن أكثر من 200 تمرين فيديو.',
    'mobile_app',
    'active',
    68000,
    false,
    3900,
    2600,
    22,
    'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    ARRAY ['Flutter', 'Firebase', 'Node.js'],
    false,
    76,
    1,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;
INSERT INTO "project" (
        id,
        title,
        "shortDescription",
        description,
        category,
        status,
        price,
        "isNegotiable",
        "monthlyRevenue",
        "monthlyProfit",
        "ageInMonths",
        "mainImage",
        "techStack",
        "isFeatured",
        "viewCount",
        "offerCount",
        "ownerId",
        "createdAt",
        "updatedAt"
    )
SELECT gen_random_uuid(),
    'لعبة موبايل كاجوال',
    'لعبة puzzle مع 50,000+ تحميل',
    'لعبة puzzle كاجوال على iOS و Android مع أكثر من 50,000 تحميل. تحقق إيرادات من الإعلانات والمشتريات داخل التطبيق. اللعبة تحصل على متوسط تقييم 4.5 نجوم.',
    'games',
    'active',
    35000,
    true,
    1800,
    1200,
    12,
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400',
    ARRAY ['Unity', 'C#', 'AdMob'],
    false,
    43,
    0,
    u.id,
    NOW(),
    NOW()
FROM "user" u
LIMIT 1;